# Generated by Django 4.2.7 on 2025-08-13 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('tipo_doc', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL'), ('PASAPORTE', 'PASAPORTE')], max_length=10, verbose_name='Tipo de Documento')),
                ('num_doc', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('importe_total_productos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe Total Productos')),
                ('total_servicio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total del Servicio')),
                ('precio_x_persona', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Persona')),
                ('fecha_vigencia', models.DateField(verbose_name='Fecha de Vigencia')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='EventoSolicitado',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('CASAMIENTO', 'Casamiento'), ('CUMPLEAÑOS', 'Cumpleaños'), ('EVENTO_COMERCIAL', 'Evento Comercial'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Evento')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('hora', models.TimeField(verbose_name='Hora del Evento')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('cantidad_personas', models.PositiveIntegerField(verbose_name='Cantidad de Personas')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='SOLICITADO', max_length=20, verbose_name='Estado')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.cliente', verbose_name='Cliente')),
                ('id_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.comprobante', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Evento Solicitado',
                'verbose_name_plural': 'Eventos Solicitados',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_personal', models.CharField(choices=[('MOZO', 'Mozo'), ('COCINERO', 'Cocinero'), ('ASISTENTE', 'Asistente'), ('SUPERVISOR', 'Supervisor')], max_length=20, verbose_name='Tipo de Personal')),
                ('nombre_y_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VACACIONES', 'Vacaciones'), ('LICENCIA', 'Licencia')], default='ACTIVO', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['tipo_personal', 'nombre_y_apellido'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Senia',
            fields=[
                ('id_senia', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('id_evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catering.eventosolicitado', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Seña',
                'verbose_name_plural': 'Señas',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['nombre_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('id_tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.tipoproducto', verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id_tipo_producto', 'descripcion'],
            },
        ),
        migrations.AddField(
            model_name='eventosolicitado',
            name='id_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.responsable', verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_personal', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Personal')),
                ('estado', models.CharField(choices=[('ASIGNADO', 'Asignado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ASIGNADO', max_length=20, verbose_name='Estado')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.eventosolicitado', verbose_name='Evento')),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'unique_together': {('id_evento', 'id_personal')},
            },
        ),
        migrations.CreateModel(
            name='MenuXTipoProducto',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_uni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Total')),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.eventosolicitado', verbose_name='Evento')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.producto', verbose_name='Producto')),
                ('id_tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.tipoproducto', verbose_name='Tipo de Producto')),
            ],
            options={
                'verbose_name': 'Menú por Tipo de Producto',
                'verbose_name_plural': 'Menús por Tipo de Producto',
                'unique_together': {('id_evento', 'id_tipo_producto', 'id_producto')},
            },
        ),
    ]
