# Generated by Django 4.2.7 on 2025-08-18 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cantidad_personal',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Personal'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('EN_SERVICIO', 'En Servicio'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado'), ('RESPONSABLE', 'Responsable'), ('CLIENTE', 'Cliente')], default='EMPLEADO', max_length=20, verbose_name='Tipo de Usuario')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['usuario__username'],
            },
        ),
    ]
