# Generated by Django 4.2.7 on 2025-09-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_cliente_usuario_eventosolicitado_precio_por_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Provincia')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='eventosolicitado',
            name='fecha_sena',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la Seña'),
        ),
        migrations.AddField(
            model_name='eventosolicitado',
            name='monto_sena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de la Seña'),
        ),
        migrations.AddField(
            model_name='eventosolicitado',
            name='observaciones_sena',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones sobre la Seña'),
        ),
        migrations.AddField(
            model_name='eventosolicitado',
            name='tiene_sena',
            field=models.BooleanField(default=False, verbose_name='¿El cliente dejó seña?'),
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Barrio')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catering.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'ordering': ['provincia__nombre', 'nombre'],
                'unique_together': {('nombre', 'provincia')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catering.barrio', verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catering.provincia', verbose_name='Provincia'),
        ),
    ]
